Repository distributed-lab/nero, pull requests merged in 2024-10, with the labels that each got.

#4 Add fast recap doc of the BitVM2
  .gitignore
  docs/images/assert-tx-taproot-output.png
  docs/images/bitvm-txs.png
  docs/images/bitvm1_chained_txs_.png
  docs/paper/bitvm2_fast_recap.pdf
  docs/paper/bitvm2_fast_recap.tex
  docs/paper/iacrtrans.cls
  docs/paper/refs.bib
  docs/paper/settings.tches.tex
  docs/paper/settings.tosc.tex
Labels: documentation

#5 👨‍💻 Add Bitcoin development environment and basic intergration tests
  .config/nextest.toml
  .github/workflows/rust.yaml
  .gitignore
  Cargo.toml
  README.md
  configs/bitcoind.conf
  docker-compose.yaml
  integration-tests/Cargo.toml
  integration-tests/src/common/mod.rs
  integration-tests/src/fetch_balance.rs
  integration-tests/src/lib.rs
Labels: documentation, feature

#10 :twisted_rightwards_arrows: Merge `bitcoin-scriptexec` from `BitVM`
  Cargo.toml
  bitcoin-scriptexec/.editorconfig
  bitcoin-scriptexec/.gitignore
  bitcoin-scriptexec/Cargo.toml
  bitcoin-scriptexec/LICENSE
  bitcoin-scriptexec/README.md
  bitcoin-scriptexec/build-wasm.sh
  bitcoin-scriptexec/src/data_structures.rs
  bitcoin-scriptexec/src/error.rs
  bitcoin-scriptexec/src/json.rs
  bitcoin-scriptexec/src/lib.rs
  bitcoin-scriptexec/src/macros.rs
  bitcoin-scriptexec/src/main.rs
  bitcoin-scriptexec/src/signatures.rs
  bitcoin-scriptexec/src/utils.rs
  bitcoin-scriptexec/src/wasm.rs
  bitcoin-splitter/src/bitvm/hash/sha256.rs
Labels: refactor

#11 🗒️ Add notes about implementation of Winternitz signing
  docs/paper/bitvm2_fast_recap.pdf
  docs/paper/bitvm2_fast_recap.tex
  docs/paper/refs.bib
Labels: documentation

#15 :memo: Update paper with a Toy Example and program split subsection
  docs/paper/bitvm2_fast_recap.pdf
  docs/paper/bitvm2_fast_recap.tex
  docs/paper/iacrtrans.cls
Labels: documentation

#17 :one: Add `u29` Arithmetic Test Script
  bitcoin-testscripts/src/lib.rs
  bitcoin-testscripts/src/u29mul.rs
Labels: feature

#20 :memo: 🌱 Update Paper and README file. Add seed support
  .gitignore
  README.md
  bitcoin-splitter/Cargo.toml
  bitcoin-splitter/src/split/intermediate_state.rs
  bitcoin-splitter/src/split/script.rs
  bitcoin-testscripts/src/int_add.rs
  bitcoin-testscripts/src/int_mul_karatsuba.rs
  bitcoin-testscripts/src/int_mul_windowed.rs
  bitcoin-testscripts/src/sha256.rs
  bitcoin-testscripts/src/square_fibonacci.rs
  bitcoin-testscripts/src/u32mul.rs
  bitcoin-utils/src/comparison.rs
  bitcoin-utils/src/pseudo.rs
  core/src/disprove/mod.rs
  core/src/disprove/signing.rs
  docs/images/icon.png
  docs/paper/nero.pdf
  docs/paper/nero.tex
  docs/paper/refs.bib
  integration-tests/src/taproot.rs
Labels: documentation

#18 :keyboard: Introduce `nero-cli`
  Cargo.toml
  README.md
  core/Cargo.toml
  core/src/assert/mod.rs
  core/src/disprove/tests.rs
  integration-tests/src/taproot.rs
  nero-cli/Cargo.toml
  nero-cli/src/cli/actions.rs
  nero-cli/src/cli/mod.rs
  nero-cli/src/config.rs
  nero-cli/src/context.rs
  nero-cli/src/main.rs
Labels: feature

#23 :lock_with_ink_pen: Implement Dynamic Winternitz Commitment Scheme
  bitcoin-winternitz/Cargo.toml
  bitcoin-winternitz/src/u32.rs
  core/src/disprove/signing.rs
  docs/paper/nero.pdf
  docs/paper/nero.tex
Labels: feature

#26 :seedling: Add constant seeds for integration tests and demo CLI
  core/src/assert/mod.rs
  integration-tests/src/taproot.rs
  nero-cli/src/cli/actions.rs
Labels: bug
